"""Everruns SDK for Python

A typed client for the Everruns API.

Quick Start:
    >>> from everruns_sdk import Everruns
    >>> client = Everruns()  # uses EVERRUNS_API_KEY
    >>> agent = await client.agents.create("assistant", "You are helpful.")
"""

from everruns_sdk.auth import ApiKey
from everruns_sdk.client import Everruns
from everruns_sdk.errors import (
    ApiError,
    AuthenticationError,
    EverrunsError,
    NotFoundError,
    RateLimitError,
    ValidationError,
)
from everruns_sdk.models import (
    Agent,
    AgentCapabilityConfig,
    AgentVersion,
    AgentVersionChangeKind,
    AgentVersionDiffResponse,
    Budget,
    BudgetCheckResult,
    BudgetPeriod,
    CapabilityInfo,
    ClientToolResult,
    Connection,
    ContentPart,
    Controls,
    CreateAgentVersionRequest,
    DeleteFileResponse,
    Event,
    ExternalActor,
    FileInfo,
    FileStat,
    ForkAgentVersionRequest,
    GrepMatch,
    GrepResult,
    InitialFile,
    LedgerEntry,
    Message,
    ResourceStats,
    ResumeSessionResponse,
    RollbackAgentVersionRequest,
    Session,
    SessionFile,
    SetDefaultAgentVersionRequest,
    SubmitToolResultsResponse,
    ToolCallInfo,
    ToolDefinition,
    TopUpRequest,
    extract_tool_calls,
    generate_agent_id,
    generate_harness_id,
    validate_agent_name,
    validate_harness_name,
)

__all__ = [
    "Everruns",
    "ApiKey",
    "EverrunsError",
    "ApiError",
    "AuthenticationError",
    "NotFoundError",
    "RateLimitError",
    "ValidationError",
    "Agent",
    "AgentCapabilityConfig",
    "AgentVersion",
    "AgentVersionChangeKind",
    "AgentVersionDiffResponse",
    "Budget",
    "BudgetCheckResult",
    "BudgetPeriod",
    "CapabilityInfo",
    "ClientToolResult",
    "Connection",
    "CreateAgentVersionRequest",
    "DeleteFileResponse",
    "FileInfo",
    "FileStat",
    "ForkAgentVersionRequest",
    "GrepMatch",
    "GrepResult",
    "LedgerEntry",
    "ResumeSessionResponse",
    "RollbackAgentVersionRequest",
    "Session",
    "SessionFile",
    "SetDefaultAgentVersionRequest",
    "SubmitToolResultsResponse",
    "ToolDefinition",
    "Message",
    "ResourceStats",
    "Event",
    "ExternalActor",
    "InitialFile",
    "ContentPart",
    "Controls",
    "ToolCallInfo",
    "TopUpRequest",
    "extract_tool_calls",
    "generate_agent_id",
    "generate_harness_id",
    "validate_agent_name",
    "validate_harness_name",
]

__version__ = "0.1.9"
