"""Everruns SDK for Python

A typed client for the Everruns API.

Call an agent from code (agent key):
    >>> from everruns_sdk import AgentClient
    >>> agent = AgentClient()  # EVERRUNS_AGENT_URL, EVERRUNS_AGENT_KEY
    >>> print(await agent.run("Hello!"))

Manage Everruns (personal access token):
    >>> from everruns_sdk import Everruns
    >>> client = Everruns()  # uses EVERRUNS_API_KEY
    >>> agent = await client.agents.create("assistant", "You are helpful.")
"""

from everruns_sdk.agent import AgentClient
from everruns_sdk.auth import ApiKey
from everruns_sdk.client import CHANGE_REASON_HEADER, MAX_CHANGE_REASON_CHARS, Everruns
from everruns_sdk.errors import (
    ApiError,
    AuthenticationError,
    EverrunsError,
    NotFoundError,
    RateLimitError,
    ValidationError,
)
from everruns_sdk.models import (
    Agent,
    AgentAnalysisResponse,
    AgentCapabilityConfig,
    AgentVersion,
    AgentVersionChangeKind,
    AgentVersionDiffResponse,
    AnalyzeAgentRequest,
    Budget,
    BudgetCheckResult,
    BudgetPeriod,
    CapabilityInfo,
    ClientToolResult,
    Connection,
    ContentPart,
    Controls,
    CreateAgentVersionRequest,
    CreateHarnessRequest,
    CreateMemoryFileRequest,
    CreateMemoryRequest,
    CreateWorkspaceRequest,
    DeleteFileResponse,
    Event,
    ExternalActor,
    FileInfo,
    FileStat,
    Finding,
    FindingLocation,
    ForkAgentVersionRequest,
    GrepMatch,
    GrepResult,
    GuardrailExample,
    GuardrailExamplesResponse,
    GuardrailsDryRunHit,
    GuardrailsDryRunRequest,
    GuardrailsDryRunResponse,
    Harness,
    HarnessExample,
    HarnessStatus,
    HealthCheckCaseResult,
    HealthCheckRun,
    HealthCheckStatus,
    HealthCheckSummary,
    InitialFile,
    LedgerEntry,
    Memory,
    MemoryFile,
    MemoryFileInfo,
    MemoryGrepResult,
    Message,
    ModelWithProvider,
    NetworkAccessList,
    ResourceStats,
    ResumeSessionResponse,
    RollbackAgentVersionRequest,
    Session,
    SessionFile,
    SetDefaultAgentVersionRequest,
    SubmitToolResultsResponse,
    ToolCallInfo,
    ToolDefinition,
    TopUpRequest,
    UpdateHarnessRequest,
    UpdateMemoryFileRequest,
    UpdateMemoryRequest,
    UpdateWorkspaceRequest,
    Workspace,
    extract_tool_calls,
    generate_agent_id,
    generate_harness_id,
    validate_agent_name,
    validate_harness_name,
)

__all__ = [
    "Everruns",
    "CHANGE_REASON_HEADER",
    "MAX_CHANGE_REASON_CHARS",
    "ApiKey",
    "EverrunsError",
    "ApiError",
    "AuthenticationError",
    "NotFoundError",
    "RateLimitError",
    "ValidationError",
    "Agent",
    "AgentClient",
    "AgentCapabilityConfig",
    "AgentAnalysisResponse",
    "AgentVersion",
    "AgentVersionChangeKind",
    "AgentVersionDiffResponse",
    "AnalyzeAgentRequest",
    "Budget",
    "BudgetCheckResult",
    "BudgetPeriod",
    "CapabilityInfo",
    "ClientToolResult",
    "Connection",
    "CreateAgentVersionRequest",
    "CreateHarnessRequest",
    "CreateMemoryFileRequest",
    "CreateMemoryRequest",
    "CreateWorkspaceRequest",
    "DeleteFileResponse",
    "FileInfo",
    "FileStat",
    "Finding",
    "FindingLocation",
    "ForkAgentVersionRequest",
    "GuardrailExample",
    "GuardrailExamplesResponse",
    "GuardrailsDryRunHit",
    "GuardrailsDryRunRequest",
    "GuardrailsDryRunResponse",
    "Harness",
    "HarnessExample",
    "HarnessStatus",
    "HealthCheckCaseResult",
    "HealthCheckRun",
    "HealthCheckStatus",
    "HealthCheckSummary",
    "GrepMatch",
    "GrepResult",
    "LedgerEntry",
    "Memory",
    "MemoryFile",
    "MemoryFileInfo",
    "MemoryGrepResult",
    "ModelWithProvider",
    "NetworkAccessList",
    "ResumeSessionResponse",
    "RollbackAgentVersionRequest",
    "Session",
    "SessionFile",
    "SetDefaultAgentVersionRequest",
    "SubmitToolResultsResponse",
    "ToolDefinition",
    "Message",
    "ResourceStats",
    "Event",
    "ExternalActor",
    "InitialFile",
    "ContentPart",
    "Controls",
    "ToolCallInfo",
    "TopUpRequest",
    "UpdateHarnessRequest",
    "UpdateMemoryFileRequest",
    "UpdateMemoryRequest",
    "UpdateWorkspaceRequest",
    "Workspace",
    "extract_tool_calls",
    "generate_agent_id",
    "generate_harness_id",
    "validate_agent_name",
    "validate_harness_name",
]

__version__ = "0.3.0"
